export const pacientes = [
  {
    dni: '12345678',
    name: 'Jorge Lopez',
    age: 89,
    globalScores: {
      juego1: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 1},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 1},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 1},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 1},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 1},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 1},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 1},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 1},
      },
      juego2: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 2},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 2},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 2},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 2},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 2},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 2},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 2},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 2},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 2},
      },
      juego3: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 3},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 3},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 3},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 3},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 3},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 3},
      },
      juego4: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 4},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 4},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 4},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 4},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 4},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 4},
      },
      juego5: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 5},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 5},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 5},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 5},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 5},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 5},
      },
    },
  },
  {
    dni: '87654321',
    name: 'Maria Rodriguez',
    age: 75,
    globalScores: {
      juego1: { 
        1: { scorecorrect: 13, scoreincorrect: 6, time: 500, facilitations: 2, game: 1},
        2: { scorecorrect: 17, scoreincorrect: 2, time: 480, facilitations: 0, game: 1},
        3: { scorecorrect: 10, scoreincorrect: 4, time: 320, facilitations: 1, game: 1},
        4: { scorecorrect: 7, scoreincorrect: 15, time: 400, facilitations: 3, game: 1},
        5: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 4, game: 1},
        6: { scorecorrect: 12, scoreincorrect: 5, time: 120, facilitations: 6, game: 1},
        7: { scorecorrect: 5, scoreincorrect: 11, time: 100, facilitations: 7, game: 1},
        8: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 8, game: 1},
      },
      juego2: { 
        1: { scorecorrect: 14, scoreincorrect: 7, time: 500, facilitations: 2, game: 2},
        2: { scorecorrect: 18, scoreincorrect: 1, time: 480, facilitations: 0, game: 2},
        3: { scorecorrect: 11, scoreincorrect: 2, time: 300, facilitations: 1, game: 2},
        4: { scorecorrect: 6, scoreincorrect: 12, time: 400, facilitations: 3, game: 2},
        5: { scorecorrect: 4, scoreincorrect: 9, time: 250, facilitations: 4, game: 2},
        6: { scorecorrect: 13, scoreincorrect: 6, time: 120, facilitations: 6, game: 2},
        7: { scorecorrect: 7, scoreincorrect: 10, time: 100, facilitations: 7, game: 2},
        8: { scorecorrect: 8, scoreincorrect: 14, time: 450, facilitations: 8, game: 2},
      },
      juego3: { 
        1: { scorecorrect: 15, scoreincorrect: 5, time: 500, facilitations: 2, game: 3},
        2: { scorecorrect: 19, scoreincorrect: 3, time: 480, facilitations: 0, game: 3},
        3: { scorecorrect: 10, scoreincorrect: 4, time: 320, facilitations: 1, game: 3},
        4: { scorecorrect: 7, scoreincorrect: 15, time: 400, facilitations: 3, game: 3},
        5: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 4, game: 3},
        6: { scorecorrect: 12, scoreincorrect: 5, time: 120, facilitations: 6, game: 3},
        7: { scorecorrect: 5, scoreincorrect: 11, time: 100, facilitations: 7, game: 3},
        8: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 8, game: 3},
      },
      juego4: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 4},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 4},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 4},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 4},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 4},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 4},
      },
      juego5: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 5},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 5},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 5},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 5},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 5},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 5},
      },
    },
  },
  {
    dni: '23456789',
    name: 'Carlos Sanchez',
    age: 68,
    globalScores: {
      juego1: { 
        1: { scorecorrect: 15, scoreincorrect: 3, time: 120, facilitations: 2, game: 1},
        2: { scorecorrect: 8, scoreincorrect: 14, time: 450, facilitations: 0, game: 1},
        3: { scorecorrect: 2, scoreincorrect: 5, time: 300, facilitations: 1, game: 1},
        4: { scorecorrect: 19, scoreincorrect: 7, time: 200, facilitations: 3, game: 1},
        5: { scorecorrect: 6, scoreincorrect: 10, time: 150, facilitations: 4, game: 1},
        6: { scorecorrect: 11, scoreincorrect: 9, time: 400, facilitations: 6, game: 1},
        7: { scorecorrect: 13, scoreincorrect: 6, time: 500, facilitations: 7, game: 1},
        8: { scorecorrect: 17, scoreincorrect: 2, time: 480, facilitations: 8, game: 1},
      },
      juego2: { 
        1: { scorecorrect: 10, scoreincorrect: 4, time: 320, facilitations: 2, game: 2},
        2: { scorecorrect: 7, scoreincorrect: 15, time: 400, facilitations: 0, game: 2},
        3: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 1, game: 2},
        4: { scorecorrect: 12, scoreincorrect: 5, time: 120, facilitations: 3, game: 2},
        5: { scorecorrect: 5, scoreincorrect: 11, time: 100, facilitations: 4, game: 2},
        6: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 6, game: 2},
        7: { scorecorrect: 14, scoreincorrect: 7, time: 500, facilitations: 7, game: 2},
        8: { scorecorrect: 18, scoreincorrect: 1, time: 480, facilitations: 8, game: 2},
      },
      juego3: { 
        1: { scorecorrect: 11, scoreincorrect: 2, time: 300, facilitations: 2, game: 3},
        2: { scorecorrect: 6, scoreincorrect: 12, time: 400, facilitations: 0, game: 3},
        3: { scorecorrect: 4, scoreincorrect: 9, time: 250, facilitations: 1, game: 3},
        4: { scorecorrect: 13, scoreincorrect: 6, time: 120, facilitations: 3, game: 3},
        5: { scorecorrect: 7, scoreincorrect: 10, time: 100, facilitations: 4, game: 3},
        6: { scorecorrect: 8, scoreincorrect: 14, time: 450, facilitations: 6, game: 3},
        7: { scorecorrect: 15, scoreincorrect: 5, time: 500, facilitations: 7, game: 3},
        8: { scorecorrect: 19, scoreincorrect: 3, time: 480, facilitations: 8, game: 3},
      },
      juego4: { 
        1: { scorecorrect: 12, scoreincorrect: 4, time: 300, facilitations: 2, game: 4},
        2: { scorecorrect: 5, scoreincorrect: 15, time: 400, facilitations: 0, game: 4},
        3: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 1, game: 4},
        4: { scorecorrect: 14, scoreincorrect: 6, time: 120, facilitations: 3, game: 4},
        5: { scorecorrect: 8, scoreincorrect: 10, time: 100, facilitations: 4, game: 4},
        6: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 6, game: 4},
        7: { scorecorrect: 16, scoreincorrect: 7, time: 500, facilitations: 7, game: 4},
        8: { scorecorrect: 18, scoreincorrect: 2, time: 480, facilitations: 8, game: 4},
      },
      juego5: { 
        1: { scorecorrect: 10, scoreincorrect: 3, time: 300, facilitations: 2, game: 5},
        2: { scorecorrect: 7, scoreincorrect: 14, time: 400, facilitations: 0, game: 5},
        3: { scorecorrect: 2, scoreincorrect: 5, time: 250, facilitations: 1, game: 5},
        4: { scorecorrect: 13, scoreincorrect: 6, time: 120, facilitations: 3, game: 5},
        5: { scorecorrect: 6, scoreincorrect: 10, time: 100, facilitations: 4, game: 5},
        6: { scorecorrect: 11, scoreincorrect: 9, time: 450, facilitations: 6, game: 5},
        7: { scorecorrect: 14, scoreincorrect: 7, time: 500, facilitations: 7, game: 5},
        8: { scorecorrect: 17, scoreincorrect: 2, time: 480, facilitations: 8, game: 5},
      },
    }
  },
  {
    dni: '98765432',
    name: 'Laura Gomez',
    age: 55,
    globalScores: {
      juego1: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 1},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 1},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 1},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 1},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 1},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 1},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 1},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 1},
      },
      juego2: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 2},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 2},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 2},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 2},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 2},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 2},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 2},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 2},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 2},
      },
      juego3: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 3},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 3},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 3},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 3},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 3},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 3},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 3},
      },
      juego4: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 4},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 4},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 4},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 4},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 4},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 4},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 4},
      },
      juego5: { 
        1: { scorecorrect: 4, scoreincorrect: 1, time: 300, facilitations: 2, game: 5},
        2: { scorecorrect: 9, scoreincorrect: 11, time: 400, facilitations: 0, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        3: { scorecorrect: 1, scoreincorrect: 3, time: 600, facilitations: 1, game: 5},
        4: { scorecorrect: 2, scoreincorrect: 4, time: 120, facilitations: 3, game: 5},
        5: { scorecorrect: 3, scoreincorrect: 7, time: 100, facilitations: 4, game: 5},
        6: { scorecorrect: 4, scoreincorrect: 7, time: 400, facilitations: 6, game: 5},
        7: { scorecorrect: 4, scoreincorrect: 8, time: 500, facilitations: 7, game: 5},
        8: { scorecorrect: 12, scoreincorrect: 0, time: 800, facilitations: 8, game: 5},
      },
    },
  },
  {
    dni: '34567890',
    name: 'Pedro Martinez',
    age: 80,
    globalScores: {
      juego1: { 
        1: { scorecorrect: 15, scoreincorrect: 3, time: 120, facilitations: 2, game: 1},
        2: { scorecorrect: 8, scoreincorrect: 14, time: 450, facilitations: 0, game: 1},
        3: { scorecorrect: 2, scoreincorrect: 5, time: 300, facilitations: 1, game: 1},
        4: { scorecorrect: 19, scoreincorrect: 7, time: 200, facilitations: 3, game: 1},
        5: { scorecorrect: 6, scoreincorrect: 10, time: 150, facilitations: 4, game: 1},
        6: { scorecorrect: 11, scoreincorrect: 9, time: 400, facilitations: 6, game: 1},
        7: { scorecorrect: 13, scoreincorrect: 6, time: 500, facilitations: 7, game: 1},
        8: { scorecorrect: 17, scoreincorrect: 2, time: 480, facilitations: 8, game: 1},
      },
      juego2: { 
        1: { scorecorrect: 10, scoreincorrect: 4, time: 320, facilitations: 2, game: 2},
        2: { scorecorrect: 7, scoreincorrect: 15, time: 400, facilitations: 0, game: 2},
        3: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 1, game: 2},
        4: { scorecorrect: 12, scoreincorrect: 5, time: 120, facilitations: 3, game: 2},
        5: { scorecorrect: 5, scoreincorrect: 11, time: 100, facilitations: 4, game: 2},
        6: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 6, game: 2},
        7: { scorecorrect: 14, scoreincorrect: 7, time: 500, facilitations: 7, game: 2},
        8: { scorecorrect: 18, scoreincorrect: 1, time: 480, facilitations: 8, game: 2},
      },
      juego3: { 
        1: { scorecorrect: 11, scoreincorrect: 2, time: 300, facilitations: 2, game: 3},
        2: { scorecorrect: 6, scoreincorrect: 12, time: 400, facilitations: 0, game: 3},
        3: { scorecorrect: 4, scoreincorrect: 9, time: 250, facilitations: 1, game: 3},
        4: { scorecorrect: 13, scoreincorrect: 6, time: 120, facilitations: 3, game: 3},
        5: { scorecorrect: 7, scoreincorrect: 10, time: 100, facilitations: 4, game: 3},
        6: { scorecorrect: 8, scoreincorrect: 14, time: 450, facilitations: 6, game: 3},
        7: { scorecorrect: 15, scoreincorrect: 5, time: 500, facilitations: 7, game: 3},
        8: { scorecorrect: 19, scoreincorrect: 3, time: 480, facilitations: 8, game: 3},
      },
      juego4: { 
        1: { scorecorrect: 12, scoreincorrect: 4, time: 300, facilitations: 2, game: 4},
        2: { scorecorrect: 5, scoreincorrect: 15, time: 400, facilitations: 0, game: 4},
        3: { scorecorrect: 3, scoreincorrect: 8, time: 250, facilitations: 1, game: 4},
        4: { scorecorrect: 14, scoreincorrect: 6, time: 120, facilitations: 3, game: 4},
        5: { scorecorrect: 8, scoreincorrect: 10, time: 100, facilitations: 4, game: 4},
        6: { scorecorrect: 9, scoreincorrect: 13, time: 450, facilitations: 6, game: 4},
        7: { scorecorrect: 16, scoreincorrect: 7, time: 500, facilitations: 7, game: 4},
        8: { scorecorrect: 18, scoreincorrect: 2, time: 480, facilitations: 8, game: 4},
      },
      juego5: { 
        1: { scorecorrect: 10, scoreincorrect: 3, time: 300, facilitations: 2, game: 5},
        2: { scorecorrect: 7, scoreincorrect: 14, time: 400, facilitations: 0, game: 5},
        3: { scorecorrect: 2, scoreincorrect: 5, time: 250, facilitations: 1, game: 5},
        4: { scorecorrect: 13, scoreincorrect: 6, time: 120, facilitations: 3, game: 5},
        5: { scorecorrect: 6, scoreincorrect: 10, time: 100, facilitations: 4, game: 5},
        6: { scorecorrect: 11, scoreincorrect: 9, time: 450, facilitations: 6, game: 5},
        7: { scorecorrect: 14, scoreincorrect: 7, time: 500, facilitations: 7, game: 5},
        8: { scorecorrect: 17, scoreincorrect: 2, time: 480, facilitations: 8, game: 5},
      },
    }
  },
];
export default pacientes;
